load prelude.maude
load taxonomynew.maude


fmod POLICY is
  including FILTERTREE .
  including ACCESS .
  including TEST .
  vars el  el1  el2 : Elem .
  var els els1  : ElemSet .
  var R : Nat .
  var E  A  P  L  : ElemSet .
  var P1  P2  P3 : Policy .
  var neels : NeElemSet .
  var t : Tree .
  var bt : BrTree .
  var ndl : NeNodeList .
  sort Policy .
  op ( _ , _ , _ , _ , _ ) : Set{Elem} Set{Elem} Set{Elem} Nat Set{Elem} -> Policy [ctor] .
  mb ( (el :\: els) with t , ((el & els)) , (el :\: els) with t, R , (el :\: els) with t ) :  Policy  .
  mb ( (el :\: els) with t , ((el \\ els)) , (el :\: els) with t, R , (el :\: els) with t ) :  Policy  .

  op entity_ : Policy -> ElemSet .
  eq entity(E , A , P , R , L) = (E) .

  op Actions_ : Policy -> ElemSet .
  eq Actions(E , A , P , R , L) = (A) .

  op purpose_ : Policy -> ElemSet .
  eq purpose(E , A , P , R , L) = P .

  op Ret_ : Policy -> Nat .
  eq Ret(E , A , P , R , L) = R .

  op Loc_ : Policy -> ElemSet .
  eq Loc(E , A , P , R , L) = L .

endfm

view Policy from TRIV to POLICY is
  sort Elt to Policy .
endv

fmod POLICYSET is
  including POLICY .
  including SET{Policy} .

  sorts PolicySet NePolicySet .
  subsort Policy < NePolicySet .
  subsort Set{Policy} < PolicySet .
  subsort NeSet{Policy} < NePolicySet .
  op { _ , _ } : NePolicySet Policy -> NePolicySet [ctor] .


endfm

***(fmod POLICY-LIST is
including POLICY .

sort NePolicyList .
subsort Policy < NePolicyList .
op singlepolicy : Policy -> NePolicyList [ctor] .
op [ _ , _ ] : NePolicyList Policy -> NePolicyList [ctor] .

endfm)

fmod COMPLIANCE is
including POLICY .
including ELEMSET .
including POLICYSET .
including SET{Elem} .
including LIST{Policy} .
including NAT .

vars P1  P2  P3  P4 : Policy .
var Ps Ps1 :  NePolicySet .
***var PSet PSet1 : NePolicySet .
vars el el1 el2 : Elem .
vars els els1 : ElemSet .
vars R1  R2 : Nat .
op (_,,_) : NePolicySet  NePolicySet  -> NePolicySet [ctor assoc ] .
op Entityjoin : NePolicySet -> NePolicySet .

eq Entityjoin(P1,,P2) = ( Join(entity(P1), entity(P2)), Inter(Actions(P1), Actions(P2)), Inter(purpose(P1), purpose(P2)), min( Ret(P1),Ret(P2)),  Inter(Loc(P1), Loc(P2)) ) .
eq Entityjoin(P1,,(P2,,Ps)) = ( Join((Join(entity(P1), entity(P2))) , entity(Ps)) , Inter((Inter(Actions(P1), Actions(P2))) , Actions(Ps)) , Inter((Inter(purpose(P1), purpose(P2))) , purpose(Ps)) , min((min(Ret(P1),Ret(P2))),Ret(Ps)) , Inter((Inter(Loc(P1), Loc(P2))) , Loc(Ps))) .


op Actionjoin :  NePolicySet -> NePolicySet .

eq Actionjoin(P1,,P2) = ( Inter(entity(P1), entity(P2)), Join(Actions(P1), Actions(P2)), Inter(purpose(P1), purpose(P2)), min( Ret(P1),Ret(P2)),  Inter(Loc(P1), Loc(P2)) )  .
eq Actionjoin(P1,,(P2,,Ps)) = ( Inter((Inter(entity(P1), entity(P2))) , entity(Ps)) , Join((Join(Actions(P1), Actions(P2))) , Actions(Ps)) , Inter((Inter(purpose(P1), purpose(P2))) , purpose(Ps)) , min((min(Ret(P1),Ret(P2))),Ret(Ps)) , Inter((Inter(Loc(P1), Loc(P2))) , Loc(Ps))) .


op Purposejoin : NePolicySet -> NePolicySet .

eq Purposejoin(P1,,P2) = ( Inter(entity(P1), entity(P2)), Inter(Actions(P1), Actions(P2)), Join(purpose(P1), purpose(P2)), min( Ret(P1),Ret(P2)),  Inter(Loc(P1), Loc(P2)) )  .
eq Purposejoin(P1,,(P2,,Ps)) = ( Inter((Inter(entity(P1), entity(P2))) , entity(Ps)) , Inter((Inter(Actions(P1), Actions(P2))) , Actions(Ps)) , Join((Join(purpose(P1), purpose(P2))) , purpose(Ps)) , min((min(Ret(P1),Ret(P2))),Ret(Ps)) , Inter((Inter(Loc(P1), Loc(P2))) , Loc(Ps)))  .


op Retjoin : NePolicySet -> NePolicySet .

eq Retjoin(P1,,P2) = ( Inter(entity(P1), entity(P2)), Inter(Actions(P1), Actions(P2)), Inter(purpose(P1), purpose(P2)), max( Ret(P1),Ret(P2)),  Inter(Loc(P1), Loc(P2)) ) .
eq Retjoin(P1,,(P2,,Ps)) = ( Inter((Inter(entity(P1), entity(P2))) , entity(Ps)) , Inter((Inter(Actions(P1), Actions(P2))) , Actions(Ps)) , Inter((Inter(purpose(P1), purpose(P2))) , purpose(Ps)) , max((max(Ret(P1),Ret(P2))),Ret(Ps)) , Inter((Inter(Loc(P1), Loc(P2))) , Loc(Ps))) .


op Locationjoin : NePolicySet -> NePolicySet .

eq Locationjoin(P1,,P2) = ( Inter(entity(P1), entity(P2)), Inter(Actions(P1), Actions(P2)), Inter(purpose(P1), purpose(P2)), min( Ret(P1), Ret(P2)),  Join(Loc(P1), Loc(P2)) ) .
eq Locationjoin(P1,,(P2,,Ps)) = ( Inter((Inter(entity(P1), entity(P2))) , entity(Ps)) , Inter((Inter(Actions(P1), Actions(P2))) , Actions(Ps)) , Inter((Inter(purpose(P1), purpose(P2))) , purpose(Ps)) , min((min(Ret(P1),Ret(P2))),Ret(Ps)) , Join((Join(Loc(P1), Loc(P2))) , Loc(Ps))) .



op _subse_ : Set{Elem} Set{Elem} -> Bool .
eq els subse els1 = els subset els1 .

op _less_ : Nat Nat -> Bool .
eq R1 less R2 = R1 < R2 .

op Inter : Set{Elem} Set{Elem} -> Set{Elem} .
eq Inter (els, els1 ) = intersection (els , els1) .

op Join : Set{Elem} Set{Elem} -> Set{Elem} .
eq Join ( els , els1) = union(els, els1) .



op _\C_ : Policy Policy -> Bool .
ceq P1 \C P2 = true if entity(P1) subse entity(P2) /\ Actions(P1) subse Actions(P2) /\  purpose(P1) subse purpose(P2) /\ Ret(P1) <= Ret(P2) /\ Loc(P1) subse Loc (P2) .
eq P1 \C P2 = false [owise] .


op subsq : Set{Elem} -> Nat .
eq subsq (els) = | els | .


op combine : NePolicySet -> NePolicySet .
eq combine (P1,,P2) = ( Entityjoin(P1,,P2) , Actionjoin(P1,,P2) , Purposejoin(P1,,P2), Retjoin(P1,,P2), Locationjoin(P1,,P2)) .
eq combine (P1,, P2,, Ps) = ( Entityjoin(P1,,P2,,Ps) , Actionjoin(P1,,P2,,Ps) , Purposejoin(P1,,P2,,Ps), Retjoin(P1,,P2,,Ps), Locationjoin(P1,,P2,,Ps)) .

op closure : NePolicySet  -> NePolicySet .
eq closure ( P1,, P2,, Ps ) = union( (P1,, P2,, Ps) , combine(P1,, P2,, Ps)) .


op complysubset : Policy NePolicySet -> NePolicySet .
ceq complysubset( P1, P2) = P2  if ( not (Inter(entity(P1), entity(P2)) == empty)) .
ceq complysubset( P1, (P2,,Ps)) =  (P2 ,, complysubset( P1, Ps)) if (complysubset( P1, P2) == P2) .
eq complysubset( P1, (P2,,Ps)) = complysubset( P1, Ps) .
eq complysubset( P1, P2) = empty [owise] .

***function for compliance between two policy entries
op complyrule1  : Policy NePolicySet -> Bool .
eq complyrule1(P1, P2 ) =  if (P1 \C P2) then true else false fi .
ceq complyrule1(P1, (P2 ,, Ps)) = true if (P1 \C P2) or complyrule1(P1 ,Ps ) .
eq complyrule1(P1, Ps ) = false .
***total compliance with policy set
op complywithset : Policy NePolicySet -> Bool .
ceq complywithset(P1, P2) = true if P1 \C P2 .
ceq complywithset( P1, (P2,,Ps)) = true if complyrule1(P1 , closure(complysubset(P1, (P2,,Ps)))) .
ceq complywithset( P1, (P2,,Ps)) = true if complyrule1(P1, (P2 ,, Ps)) == true .
eq complywithset( P1, (P2,,Ps)) = false [owise] .
***total compliance between two policy sets
op totalCompl : NePolicySet NePolicySet -> Bool .
eq totalCompl(P1, Ps1) = if complywithset( P1, Ps1) then true else false fi .
eq totalCompl((P1,,P2), Ps1) = if complywithset( P1, Ps1) and complywithset( P2, Ps1) == true  then true else false fi .
ceq totalCompl((P1,,P2,,Ps), Ps1) = true if complywithset( P1, Ps1) == true  /\  complywithset( P2, Ps1)== true  /\  complywithset( Ps, Ps1) == true  .
eq totalCompl((P1,,P2,,Ps), Ps1) = false [owise] .

endfm

***This module declares example polcies to check the policy compliance.
fmod TESTING is
  including FILTERTREE .
  including POLICY .
  including COMPLIANCE .

  ops PE1 PE2 PE3 PE4 PE5 PE6 PE7 PL PL1 PL2 PL3 : -> Policy .

  eq PE1 = ( doctor with entityTr , (Use & Store) , (healthServ :\: marketing,admin) with purposeTr , 200 , Europe with locationTr ) .
  eq PE2 = ( (hospital :\: admin ) with entityTr , (Use & Store & Collect), treatm with purposeTr , 300 , Europe with locationTr ) .
  eq PE3 = ( doctor with entityTr , ( Use & Store & Transfer), (healthServ :\: marketing,billing) with purposeTr , 200  , Europe with locationTr) .

  eq PE4 = (doctor with entityTr , (Use & Store & Collect) , healthServ with purposeTr  , 200 ,Europe with locationTr ) .
  eq PE5 = ((hospital :\: marketing ) with entityTr ,( Use & Transfer) , healthServ with purposeTr , 300 , Europe with locationTr ) .
  eq PE6 = (healthAsso with entityTr , (Use & Store & Collect) , treatm with purposeTr , 300 , Europe with locationTr ) .

  eq PL = ((hospital :\: admin ) with entityTr,(Use),  treatm with purposeTr ,100 , Europe with locationTr ) .
  eq PL1 = (doctor with entityTr , (Use), spcltreatm with purposeTr ,100 , Europe with locationTr ) .
  eq PL2 = (doctor with entityTr , (Use & Store & Transfer), spcltreatm with purposeTr ,100 , Europe with locationTr ) .
  eq PL3 = (others with entityTr , (Use & Store & Transfer), spcltreatm with purposeTr ,100 , Europe with locationTr ) .

endfm
